---
title: "Proyecto de Supervivencia TITANIC"
output: html_notebook
#author: "David Bujosa"
---


# Estudio de los algoritmos de clasificación


```{r}
# cargar la librerias del proyecto
library(rpart)
library(rattle)
library(RColorBrewer)
```

Se le proporciona un fichero de nombre “train.csv” que contiene 4 columnas con valores numéricos
y categóricos. Las variables son

Exersice 1
```{r}
train <- read.delim("./data/train.csv", sep = "\t", head = TRUE)
rownames(train) <- train$id
train$id <- NULL

head(train)
```

La función para crear árboles de decisión que vamos a utilizar es rpart. Teclee en la consola 
help(“rpart”) y estudie como aplicarla

```{r}
# Help library rpart
help(rpart)
tree <- rpart(Survived~. ,  data = train, method ="class") # nolint
```

Exersice 3
```{r}
# Visualice el resultado usando la función plot.
fancyRpartPlot(tree)
```

Exersice 4
```{r}
test <- read.delim("./data/test.csv", sep = "\t", head = TRUE)
rownames(test) <- test$id
test$id <- NULL

head(test)
dim(test)
colnames(test)

#Predice los valores
pred <- predict(tree, test,type = "class")

#Construye la matrix de prediccion
conf <- table(Survived, pred, "class")

#Calculate accuracy
acc <- sum(diag(conf)) / sum(conf)
print(acc)
```

Exersice 5
```{r}
set.seed(1)
tree2 <- rpart(Survived ~., train, "class", control=rpart.control(cp=0.00001))

#Dibuja el árbol de decisión
fancyRpartPlot(tree2)

# poda el arbol
pruned <- prune(tree2, cp = 0.01)

#Dibuja el pruned
fancyRpartPlot(pruned)
```

